$(document).ready(function(){
    $('#hide').click(function(){
       $('#div1').hide();
    })
    $('#show').click(function(){
       $('#div1').show();
    })
    $('#toggle').click(function(){
       $('#div1').toggle();
    })
})